### ISSUE TITLE
Introducing this repo for talk requests/offers

### ISSUE THREAD

**Issue by FlxVctr** [pyhamburg/talks#1]
## Is this a talk you want to hold, or are you interested in somebody holding a talk?

I could give this talk as I have some experience with the talk repo by the Python User Group in Brisbane.

## Description

It will be a pretty short talk introducing the repo. Most likely a 5 minute walk through of requesting a talk on a topic I'm interested in. Maybe we might have a short discussion to get feedback and suggestions on possible labels and a possibility for people who do not want to sign up for GitHub (most likely just the old way of contacting the organisers directly).

**Comment by brakhane** [comment]
Would you be available at the coming meeting (it will probably be on a Thursday this time: 27th)

**Comment by FlxVctr** [comment]
I just saw the invitation (now for Wednesday). Yes, as it stands, I should be available.

**Comment by FlxVctr** [comment]
just gave this talk. no slides, sry.
