### ISSUE TITLE
Lightweight profiling

### ISSUE THREAD

**Issue by krenzlin** [pyhamburg/talks#5]
#### Is this a talk you want to hold or are you interested in somebody talking about this topic?
I want to give this talk

#### In case you hold the talk, how long will the talk roughly be?

approx. 10 min just presenting the ideas and a simple live demo

## Description

While profiling should be a common tool for every programmer it is often neglected because of the huge performance overhead of traditional deterministic profilers, like cProfile.
Statistical or sampling profilers tackle this problem by trading resolution allowing profiling in production.
I want to present a short and simple implementation that has been in use for several years now.

**Comment by brakhane** [comment]
@krenzlin Would you be able to hold this talk next week, 23rd?

**Comment by krenzlin** [comment]
Can do. Might be a bit improvised though.

**Comment by brakhane** [comment]
OK, thanks
