### ISSUE TITLE
Peeking under the hood of class construction

### ISSUE THREAD

**Issue by Ed-von-Schleck** [pyhamburg/talks#8]
## Administrative Info

* [x] I'd like to hold this talk
* [ ] I'd like somebody to talk about this topic, but can't do it myself

#### Talk length

* [ ] 5-15 Minutes
* [ ] 15-30 Minutes
* [x] 30-45 Minutes
* [ ] 45-60 Minutes

## Description

Let's talk about classes. What _are_ they really? We peek under the hood of class construction and member access, and maybe deconstruct some ideological ideas about object-oriented programming along the way. Then we'll take it way too far and do stuff nobodoy should have any reason to do – but we do it anyways, just because Python allows us to, and we might learn a thing or two about the very dynamic nature of Python.

**Comment by brakhane** [comment]
Hi. Are you able to hold this talk next Tuesday? Also, do you think it would be suitable for the beginner slot or for the general one?

**Comment by Ed-von-Schleck** [comment]
Hey, I was submitting this based on a request from Nefta. This is beginner-ish, and yes, I'm can hold this talk on tuesday.

Thanks for organizing the meetup!

**Comment by brakhane** [comment]
OK, I'll update the meetup data then. Thank you too for holding a talk
